TUNING.MYWD = {
    GHOSTLYELIXIR_MYWD_MOON_DAMAGE = 100,
    GHOSTLYELIXIR_MYWD_MOON_DEFENSE = 100,
    GHOSTLYELIXIR_MYWD_MOON_DURATION = 10,
    -- GHOSTLYELIXIR_MYWD_MOON_DURATION = TUNING.TOTAL_DAY_TIME,

    GHOSTLYELIXIR_MYWD_SHADOW_DAMAGE = 100,
    GHOSTLYELIXIR_MYWD_SHADOW_DEFENSE = 100,
    GHOSTLYELIXIR_MYWD_SHADOW_DURATION = 10,
    -- GHOSTLYELIXIR_MYWD_SHADOW_DURATION = TUNING.TOTAL_DAY_TIME,



    WENDY_AURA_RADIUS = 4,
    WENDY_AURA_TICKPERIOD = 1.5,
    WENDY_SHADOW_DAMAGE_MOD = 2,

    ABIGAIL_SHADOW_DAMAGE_MOD_ADD = 0,
    -- ABIGAIL_BASE_PLANARDEFENSE = 0,
    -- ABIGAIL_BASE_PLANARDAMAGE = 0,
}
