TUNING.MYWD = {
    GHOSTLYELIXIR_MOON_DAMAGE = 9.99,
    GHOSTLYELIXIR_MOON_DEFENSE = 999,
    GHOSTLYELIXIR_MOON_DURATION = TUNING.TOTAL_DAY_TIME,



    -- ABIGAIL_MOON_IMPACT_ATTACK = 9.99,
    -- ABIGAIL_MOON_IMPACT_SPEED = 20,
    ABIGAIL_MOON_IMPACT_DISTANCE = 8,
    ABIGAIL_MOON_IMPACT_DURATUION = 0.5,
    ABIGAIL_MOON_IMPACT_GUARD_RANGE = 16,
    ABIGAIL_MOON_IMPACT_SLEEP = 1.5,
    ABIGAIL_MOON_IMPACT_WALK_TIMEOUT = 0.01,
}


--------------------------------------------------------------------------------------------------------------------
-- MYWD:下面代码复制粘贴自测试服代码不要动，等更新了可以删了
local total_day_time = TUNING.TOTAL_DAY_TIME
local seg_time = TUNING.SEG_TIME

-- Wendy Skill Tree
TUNING.ABIGAIL_GESTALT_DAMAGE =
{
    day = 100,
    dusk = 150,
    night = 250,
}

TUNING.ABIGAIL_SHADOW_PLANAR_DAMAGE =
{
    day = 15,
    dusk = 20,
    night = 40,
}

TUNING.ABIGAIL_GESTALT_HIDE_THRESHOLD = 0.25

TUNING.WENDYSKILL_COMMAND_COOLDOWN = 4
TUNING.WENDYSKILL_ESCAPE_TIME = 1.5
TUNING.WENDYSKILL_DASHATTACK_VELOCITY = 14.0
TUNING.WENDYSKILL_DASHATTACK_HITRATE = 0.5

TUNING.WENDYSKILL_SMALLGHOST_EXTRACHANCE = 0.10
TUNING.WENDYSKILL_GRAVESTONE_DECORATECOUNT = 3
TUNING.WENDYSKILL_GRAVESTONE_DECORATETIME = 6 * total_day_time
TUNING.WENDYSKILL_GRAVESTONE_GHOSTCOUNT = 4
TUNING.WENDYSKILL_GRAVESTONE_EVILFLOWERCOUNT = 3
TUNING.WENDYSKILL_GRAVEGHOST_DEADTIME = total_day_time
TUNING.WENDYSKILL_GRAVEGHOST_AURARADIUS = 2.5

TUNING.WENDYSKILL_SISTURN_SANITY_MODIFYER = 0.75
TUNING.WENDY_SISTURN_PETAL_PRESRVE = 0.5

TUNING.GHOSTLYELIXIR_PLAYER_SLOWREGEN_HEALING = 1
TUNING.GHOSTLYELIXIR_PLAYER_SLOWREGEN_TICK_TIME = 1
TUNING.GHOSTLYELIXIR_PLAYER_SLOWREGEN_DURATION = 20 -- 20 hp

TUNING.GHOSTLYELIXIR_PLAYER_FASTREGEN_HEALING = 5
TUNING.GHOSTLYELIXIR_PLAYER_FASTREGEN_TICK_TIME = 1
TUNING.GHOSTLYELIXIR_PLAYER_FASTREGEN_DURATION = 20 -- 100 hp

TUNING.GHOSTLYELIXIR_PLAYER_DAMAGE_DURATION = total_day_time

TUNING.GHOSTLYELIXIR_PLAYER_SPEED_LOCO_MULT = 1.75
TUNING.GHOSTLYELIXIR_PLAYER_SPEED_DURATION = total_day_time
TUNING.GHOSTLYELIXIR_PLAYER_SPEED_PLAYER_GHOST_DURATION = 3

TUNING.GHOSTLYELIXIR_PLAYER_SHIELD_DURATION = seg_time * 4
TUNING.GHOSTLYELIXIR_PLAYER_SHIELD_REDUCTION = 50

TUNING.GHOSTLYELIXIR_PLAYER_RETALIATION_DAMAGE = 20
TUNING.GHOSTLYELIXIR_PLAYER_RETALIATION_DURATION = total_day_time

TUNING.GHOSTLYELIXIR_PLAYER_REVIVE_DURATION = 0.3

TUNING.GHOSTLYELIXIR_PLAYER_DRIP_FX_DELAY = seg_time / 2
