TUNING.MYWD = {
    -- 月亮药数值
    GHOSTLYELIXIR_MYWD_MOON_DAMAGE = 50,
    GHOSTLYELIXIR_MYWD_MOON_DEFENSE = 100,
    GHOSTLYELIXIR_MYWD_MOON_DURATION = TUNING.TOTAL_DAY_TIME,

    -- 暗影药数值
    GHOSTLYELIXIR_MYWD_SHADOW_DAMAGE = 50,
    GHOSTLYELIXIR_MYWD_SHADOW_DEFENSE = 100,
    GHOSTLYELIXIR_MYWD_SHADOW_DURATION = TUNING.TOTAL_DAY_TIME,



    -- 温蒂范围攻击半径
    WENDY_AURA_RADIUS = 4,
    -- 温蒂范围攻击间隔/秒
    WENDY_AURA_TICKPERIOD = 2,
    -- 暗影形态下阿比加伤倍率
    WENDY_SHADOW_DAMAGE_MOD = 2,

    -- 暗影形态下阿比加伤
    ABIGAIL_SHADOW_DAMAGE_MOD_ADD = 6,
    -- ABIGAIL_BASE_PLANARDEFENSE = 0,
    -- ABIGAIL_BASE_PLANARDAMAGE = 0,
}
