-- 美梦药剂buff的持续时间
TUNING.MYWD_GHOSTLYELIXIR_DREAM_DURATION = 16 * 30

-- 美梦药剂buff增加位面伤害
TUNING.MYWD_GHOSTLYELIXIR_DREAM_PLANARDAMAGE = 100

-- 美梦药剂buff增加位面防御
TUNING.MYWD_GHOSTLYELIXIR_DREAM_PLANARDEFENSE = 100
